# Chronologically specify the pipeline stages to run
stages:
  - lint

# Common settings for linters to avoid code repetition
# Needs can be used to specify dependencies
# Allow failure is whether the pipeline succeeds on failure or not
.lint-default: &lint-default
  stage: lint
  needs: []
  services: []
  allow_failure: false

Lint shell scripts:
  <<: *lint-default
  image: koalaman/shellcheck-alpine:latest
  before_script:
    - apk add fd
  script:
    - printf 'Running shellcheck:'
    - printf '%s\n' 'https://github.com/koalaman/shellcheck/wiki/Checks'
    - fd --extension sh --exec shellcheck

#  Keep the python version in sync with what's in production
#  Consider using black instead?
Lint python scripts:
  <<: *lint-default
  image: python:3.10-alpine
  before_script:
    - apk add --no-cache --virtual .deps gcc musl-dev
    - pip install black
  script:
    - black --check --diff --exclude=migrations .
